language: csharp
solution: BrokenDiscord.sln
before_install:
	- sudo apt-get install nunit-console
before_script:
	- nuget restore BrokenDiscord.sln
after_script:
	- nunit-console BrokenDiscord.Test/bin/Release/BrokenDiscord.Test.dll